-- MySQL Script generated by MySQL Workbench
-- Mon Aug  4 17:03:22 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema moviebookingdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema moviebookingdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `moviebookingdb` DEFAULT CHARACTER SET latin1 ;
USE `moviebookingdb` ;

-- -----------------------------------------------------
-- Table `moviebookingdb`.`bookings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moviebookingdb`.`bookings` (
  `BookingID` INT(11) NOT NULL AUTO_INCREMENT,
  `UserID` INT(11) NULL DEFAULT NULL,
  `ShowtimeID` INT(11) NULL DEFAULT NULL,
  `NumberOfTickets` INT(11) NULL DEFAULT NULL,
  `BookingDate` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`BookingID`),
  INDEX `UserID` (`UserID` ASC) VISIBLE,
  INDEX `ShowtimeID` (`ShowtimeID` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `moviebookingdb`.`movies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moviebookingdb`.`movies` (
  `MovieID` INT(11) NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(100) NOT NULL,
  `Genre` VARCHAR(50) NULL DEFAULT NULL,
  `Duration` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`MovieID`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `moviebookingdb`.`showtimes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moviebookingdb`.`showtimes` (
  `ShowtimeID` INT(11) NOT NULL AUTO_INCREMENT,
  `MovieID` INT(11) NULL DEFAULT NULL,
  `TheatreID` INT(11) NULL DEFAULT NULL,
  `ShowDate` DATE NULL DEFAULT NULL,
  `Showtime` TIME NULL DEFAULT NULL,
  `movies_MovieID` INT(11) NOT NULL,
  PRIMARY KEY (`ShowtimeID`, `movies_MovieID`),
  INDEX `MovieID` (`MovieID` ASC) VISIBLE,
  INDEX `TheatreID` (`TheatreID` ASC) VISIBLE,
  INDEX `fk_showtimes_movies_idx` (`movies_MovieID` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `moviebookingdb`.`theatres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moviebookingdb`.`theatres` (
  `TheatreID` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NULL DEFAULT NULL,
  `Location` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`TheatreID`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `moviebookingdb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moviebookingdb`.`users` (
  `UserID` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`UserID`),
  UNIQUE INDEX `Email` (`Email` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `moviebookingdb`.`theatres_has_showtimes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moviebookingdb`.`theatres_has_showtimes` (
  `theatres_TheatreID` INT(11) NOT NULL,
  `showtimes_ShowtimeID` INT(11) NOT NULL,
  `showtimes_movies_MovieID` INT(11) NOT NULL,
  PRIMARY KEY (`theatres_TheatreID`, `showtimes_ShowtimeID`, `showtimes_movies_MovieID`),
  INDEX `fk_theatres_has_showtimes_showtimes1_idx` (`showtimes_ShowtimeID` ASC, `showtimes_movies_MovieID` ASC) VISIBLE,
  INDEX `fk_theatres_has_showtimes_theatres1_idx` (`theatres_TheatreID` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `moviebookingdb`.`users_has_bookings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moviebookingdb`.`users_has_bookings` (
  `users_UserID` INT(11) NOT NULL,
  `bookings_BookingID` INT(11) NOT NULL,
  PRIMARY KEY (`users_UserID`, `bookings_BookingID`),
  INDEX `fk_users_has_bookings_bookings1_idx` (`bookings_BookingID` ASC) VISIBLE,
  INDEX `fk_users_has_bookings_users1_idx` (`users_UserID` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `moviebookingdb`.`showtimes_has_bookings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moviebookingdb`.`showtimes_has_bookings` (
  `showtimes_ShowtimeID` INT(11) NOT NULL,
  `showtimes_movies_MovieID` INT(11) NOT NULL,
  `bookings_BookingID` INT(11) NOT NULL,
  PRIMARY KEY (`showtimes_ShowtimeID`, `showtimes_movies_MovieID`, `bookings_BookingID`),
  INDEX `fk_showtimes_has_bookings_bookings1_idx` (`bookings_BookingID` ASC) VISIBLE,
  INDEX `fk_showtimes_has_bookings_showtimes1_idx` (`showtimes_ShowtimeID` ASC, `showtimes_movies_MovieID` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
